
CREATE TABLE Produkt(	
	P_ID  CHAR(10) NOT NULL,
	Titel VARCHAR(120) NOT NULL,
	Verkaufsrang INT,
	Bild VARCHAR(150),
	PRIMARY KEY(P_ID)
);

CREATE TABLE Aehnlich(  
	Produkt_ID CHAR(10) NOT NULL,
	Aehnlich_ID CHAR(10) NOT NULL,
	PRIMARY KEY(Produkt_ID , Aehnlich_ID),
	FOREIGN KEY(Produkt_ID) REFERENCES Produkt
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY (Aehnlich_ID) REFERENCES Produkt
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE Kategorie(		
	Kategorie_ID INT NOT NULL,
	Name VARCHAR(50) NOT NULL,
	PRIMARY KEY(Kategorie_ID)
);

              
CREATE TABLE Produkt_Kategorie(	
	Produkt_ID CHAR(10) NOT NULL,
	Kategorie_ID INT NOT NULL,
	PRIMARY KEY(Produkt_ID, Kategorie_ID),
	FOREIGN KEY(Produkt_ID) REFERENCES Produkt
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY(Kategorie_ID) REFERENCES Kategorie
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE Oberkategorie(
	Kategorie_ID INT NOT NULL,
	Oberkategorie_ID INT,
	PRIMARY KEY(Kategorie_ID , Oberkategorie_ID),
	FOREIGN KEY(Kategorie_ID ) REFERENCES Kategorie
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY(Oberkategorie_ID) REFERENCES Kategorie
	ON UPDATE CASCADE
	ON DELETE SET NULL
);

CREATE TABLE DVD(
	Produkt_ID CHAR(10) NOT NULL,		
	Laufzeit INT NOT NULL,
	Format VARCHAR(100) NOT NULL,
	Regioncode VARCHAR(10) NOT NULL,
	PRIMARY KEY(Produkt_ID),
	FOREIGN KEY(Produkt_ID) REFERENCES Produkt
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE Musik(
	Produkt_ID CHAR(10) NOT NULL,
	Label VARCHAR(50) NOT NULL,
	Erscheinungsjahr int NOT NULL,
	PRIMARY KEY(Produkt_ID),
	FOREIGN KEY(Produkt_ID) REFERENCES Produkt
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE Buch (	
	Produkt_ID CHAR(10) NOT NULL,
	ISBN CHAR(13) NOT NULL,
	Erscheinungsdatum DATE NOT NULL,
	Seitenzahl INT CHECK (Seitenzahl > 0),
	Verlag VARCHAR(50) NOT NULL,
	PRIMARY KEY(Produkt_ID),
	FOREIGN KEY(Produkt_ID) REFERENCES Produkt
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE Medienperson(	
	Name VARCHAR(50)NOT NULL,
	PRIMARY KEY(Name)
);

CREATE TABLE Buch_Autor (	
	Produkt_ID CHAR(10) NOT NULL,
	Name VARCHAR(50) NOT NULL,
	PRIMARY KEY(Name, Produkt_ID),
	FOREIGN KEY(Name) REFERENCES Medienperson
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
	FOREIGN KEY(Produkt_ID) REFERENCES Buch
	ON UPDATE CASCADE
	ON DELETE RESTRICT
);

CREATE TABLE Musik_Kuenstler ( 
	Produkt_ID CHAR(10) NOT NULL,
	Name VARCHAR(80)NOT NULL,
	PRIMARY KEY(Name, Produkt_ID),
	FOREIGN KEY(Name) REFERENCES Medienperson
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
	FOREIGN KEY(Produkt_ID) REFERENCES Musik
	ON UPDATE CASCADE
	ON DELETE RESTRICT
);

CREATE TABLE DVD_Beteiligung(
	Produkt_ID CHAR(10) NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Rolle VARCHAR(50) NOT NULL,
	PRIMARY KEY(Name,  Produkt_ID, Rolle),
	FOREIGN KEY(Name) REFERENCES Medienperson
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
	FOREIGN KEY(Produkt_ID) REFERENCES DVD
	ON UPDATE CASCADE
	ON DELETE RESTRICT
);

CREATE TABLE Lieder(
	Produkt_ID CHAR(10) NOT NULL,
	Name VARCHAR(150) NOT NULL,
	PRIMARY KEY(Produkt_ID, Name),
	FOREIGN KEY(Produkt_ID) REFERENCES Musik
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE Kunde (	
	K_ID VARCHAR(20) NOT NULL,
	Lieferadresse VARCHAR(50) NOT NULL,
	Konto INT NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Geburtsdatum DATE NOT NULL,
	PRIMARY KEY(K_ID)
);

CREATE TABLE Kauf (	
	Kunden_ID VARCHAR(20) NOT NULL,
	Filial_ID INT NOT NULL,
	Produkt_ID CHAR(10) NOT NULL,
	Zeitstempel TIMESTAMP NOT NULL,
	Preis FLOAT NOT NULL,
	Menge INT NOT NULL,
	Ort VARCHAR(30) NOT NULL, 	
	Strasse VARCHAR(60) NOT NULL,
	PLZ INT NOT NULL,
	PRIMARY KEY(Kunden_ID, Filial_ID, Produkt_ID, Zeitstempel),
	FOREIGN KEY(Kunden_ID) REFERENCES Kunde
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
	FOREIGN KEY(Produkt_ID) REFERENCES Produkt
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
	FOREIGN KEY(Filial_ID) REFERENCES Filiale
	ON UPDATE CASCADE
	ON DELETE RESTRICT
);				

CREATE TABLE Filiale (
	F_ID VARCHAR(20) NOT NULL,
	Primary KEY(F_ID)
);

CREATE TABLE Angebot (	
	Filial_ID VARCHAR(20) NOT NULL,
	Produkt_ID CHAR(10) NOT NULL,
	Zustand VARCHAR(20) NOT NULL,
	Preis FLOAT NOT NULL,
	Verfuegbarkeit VARCHAR(20),
	PRIMARY KEY (Filial_ID, Produkt_ID),
	FOREIGN KEY (Filial_ID) REFERENCES Filiale
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY (Produkt_ID) REFERENCES Produkt
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE Review (	
	Produkt_ID CHAR(10) NOT NULL,
	Kunden_ID VARCHAR(20) NOT NULL,
	Punkte INT DEFAULT 0 CHECK (Punkte  BETWEEN 0 AND 5),
	Rezension TEXT,
	Inhalt Text,
	PRIMARY KEY (Produkt_ID,Kunden_ID),
	FOREIGN KEY (Produkt_ID) REFERENCES Produkt
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	FOREIGN KEY (Kunden_ID) REFERENCES Kunde
	ON DELETE CASCADE
	ON UPDATE CASCADE
)



